# Generated by Django 3.1.5 on 2021-01-24 10:41

from django.db import migrations, models
import django.db.models.deletion
import infoadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(max_length=50)),
                ('timestamp_start_process', models.DateTimeField(auto_now_add=True)),
                ('timestamp_end_process', models.DateTimeField()),
                ('bar_code_1', models.FilePathField(path=infoadmin.models.barcode_images_path)),
                ('bar_code_2', models.FilePathField(path=infoadmin.models.barcode_images_path)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoadmin.machines')),
            ],
        ),
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('defect_image_1', models.FilePathField(path=infoadmin.models.defects_images_path)),
                ('defect_image_2', models.FilePathField(path=infoadmin.models.defects_images_path)),
                ('defect', models.TextField()),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoadmin.rolls')),
            ],
        ),
    ]
