# Generated by Django 3.1.5 on 2021-01-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='is_use_roll',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolls',
            name='timestamp_end_process',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
