# Generated by Django 3.1.5 on 2021-01-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoadmin', '0002_auto_20210124_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolls',
            name='cycles',
            field=models.IntegerField(default=0),
        ),
    ]
