# Generated by Django 3.1.6 on 2021-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoadmin', '0003_rolls_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='defect_image_1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='defects',
            name='defect_image_2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='rolls',
            name='bar_code_1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='rolls',
            name='bar_code_2',
            field=models.ImageField(upload_to=''),
        ),
    ]
